"""create artist table

Revision ID: 06e378c47da9
Revises: 94e5bff5a90c
Create Date: 2025-07-24 14:30:45.790924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e378c47da9'
down_revision: Union[str, Sequence[str], None] = '94e5bff5a90c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_data', sa.Column('price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_data', 'price')
    # ### end Alembic commands ###
